### ISSUE TITLE
Multilingual config does not work

### ISSUE THREAD

**Issue by ochrons** [zhaoda/gitbook-plugin-editlink#1]
If I add `"multilingual": false` to my config, I get

```
Error: Configuration Error: pluginsConfig.editlink.multilingual is not one of enum values: true,false
```

Removing the config variable solves the issue, since the default seems to be `false`

Gitbook 2.5 on Windows

**Comment by zhaoda** [comment]
I have update package.json, please run `gitbook install` to update the plugin.
